version: '3.1'

services:

  postgres:
    image: postgres:15.2
    restart: always
    container_name: hermes_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"